language: generic

sudo: required

matrix:
  include:
    - dist: trusty
      env: COQ_VERSION="trunk"  TARGETS="fiat-core parsers"                 FLAGS="PROFILE=1" COQ_PACKAGE="coq libcoq-ocaml-dev ocaml camlp5"                                   PPA="ppa:jgross-h/coq-trunk-daily"

before_install:
  - if [ ! -z "$PPA" ]; then sudo add-apt-repository "$PPA" -y; fi
  - sudo apt-get update -q
  - sudo apt-get install $COQ_PACKAGE -y

script: ./etc/coq-scripts/timing/make-pretty-timed.sh -j2 $TARGETS $FLAGS && make TIMED=1 -j2 $TARGETS
